apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
data:
  TASK_SERVICE_URL: "http://task-service:8001"
  REDIS_HOST: "redis"
  ALLOWED_ORIGINS: "http://20.204.221.103/"